### ISSUE TITLE
How to convert if react redux components into web component?

### ISSUE THREAD

**Issue by Harishreddylv** [bitovi/react-to-web-component#109]
I am using r2wc to convert react components into web component. I can able to convert if the component not using any redux. But it shows an error when the component uses redux showing below error.  With redux it should work properly, how to achieve this

![image](https://github.com/bitovi/react-to-web-component/assets/44708880/a5df99b1-0685-47d9-b554-ac5fc2ba7196)

**Comment by zerico007** [comment]
Can you provide more info? Are you using redux for state management in a single component? If so, why not use local state management? Also, is your component directly wrapped in a Provider in it's definition? If so, redux won't work since converting your React component to a web component essentially isolates and encapsulates the component. You can also look into using zustand for state management - this doesn't require a provider and will work when your component is converted to a web component.

**Comment by christopherjbaker** [comment]
My best guess is that you are putting the Redux context in one WC and putting the consumer in another. React Contexts are limited to the instance of React, so you can't share a context like that. If you need this, you can create the Redux store directly, then put it on the window, and have your WCs grab it from the window and pass it to the [Redux Provider](https://react-redux.js.org/api/provider).

Since we haven't heard anything in a while, I'm going to close this issue, but will happily re-open it if you or others need assistance here.
