### ISSUE TITLE
Add 'WebComponentProps' with an optional property 'shadowRoot' and 'parentNode' that is a ref of the custom  HTMLElement 

### ISSUE THREAD

**Issue by Yukooo** [bitovi/react-to-web-component#61]
To provide more flexibility when using shadow Dom (mainly for CCS encapsulation), it would really help to pass an extra property to the react root component, which is a reference to the object returned by "self.attachShadow({mode: options.shadow })".

Here is an example to get a better view:

```
import React from 'react'
import reactToWebComponent from 'react-to-webcomponent'

// this type comes from 'react-to-webcomponent' like
// import WebComponentProps from 'react-to-webcomponent'
type WebComponentProps = {
    shadowRoot?: HTMLElement // it is null if no option 'shadow' is defined
}

// my custome prop type for the root component
type MyCustomProps = WebComponentProps & {
    userName: string // that should be taken from the customs attribute like user-name="Alex"
}

// this a simple React.FC that should be wrapped by the 'react-to-webcomponent'
const App: React.FC<MyCustomProps> = (props) => {

    const emotionRoot = document.createElement("style");
    emotionRoot.setAttribute('id', 'hidden-style')
    emotionRoot.setAttribute('type', 'text/css')
    emotionRoot.innerHTML = `h1 { color: blue;}`

    props?.shadowRoot?.appendChild(emotionRoot)
    return <h1>Hello {props.userName}</h1>;
}

// @ts-ignore
customElements.define('my-custome-web-element', reactToWebComponent(App, React, ReactDOMClient, {
    shadow: 'closed',
    props: {
        userName: String
    }
}))
```

If on the App component we have a ref to shadowRoot then we can add styles directly to it.
Especially it is useful if the MUI lib v.5  is used, because according to their [**guide**](https://mui.com/material-ui/guides/shadow-dom/) to make it properly work in the shadowDom we have to use a cache like
```
const cache = createCache({
  key: 'css',
  prepend: true,
  container: emotionRoot,
})
// and then 
...
 <CacheProvider value={cache}>
    <App />
  </CacheProvider>,
...
```
Also we need a shadowRoot to create a root div if we want to use MUI components like Menu, Dialog, Popover

**Comment by christopherjbaker** [comment]
React is mounted on that root element, so any direct manipulation of its contents will create problems for React. The safer option would be to render that `<style />` element in your JSX, then use a ref to access the element and pass that to MUI / etc.

**Comment by yk-jemmic** [comment]
@christopherjbaker I really appreciate your prompt reply.

Pardon my toxicity, but I have a strong feeling that you have never tried the approach you suggested and your claim about "_any direct manipulation of its contents will create problems for Reac_t" is not justified, thereby misleading our other colleagues who might just take your word for it. 

For me personally, what you did helped a lot at the beginning when I offered my team a convenient mechanism for a gradual transition from JSP/JSF to reactJS and for this I want to express my deep gratitude to you, good job!


I won't go into details but what you said just doesn't work for at least two significant reasons.
As a result, all your work has simply lost its value namely a reliable mechanism that would allow devs to safely and quickly have several completely different encapsulated approaches to UI rendering, while providing transparent communication between them as well as bypassing unnecessary workarounds, since in the end it is only transitional stage with further complete replacement.


PS. Anyway, thanks again for your work, it was a good starting point for me (especially for someone new to React that time). 
For me this is no longer a problem.

**Comment by christopherjbaker** [comment]
My concerns are for the same reason that you can't pass `document.body` to `ReactDOM.createRoot`:
> Creating roots directly with document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try using a container element created for your app.

However I'm not sure what other option we have here, besides making people fuss with their own container and ref (as I suggested above) or always rendering components an extra div deeper (which is a terrible idea). We'll have a solution for this in v2, likely exposing shadowRoot/container as you've suggested.

**Comment by Yukooo** [comment]
@christopherjbaker  
Long story short, I needed shadow ==closed because I had to work with very crapy outdated JSP + giant messy CSS+JavaScript accumulated over 15 years (against this background, even Dumbledore looks like a failed childish magician) and all this affected my beauty in my MUI react app.

And MUI is also quite a big thing that requires special attention.

So here is an example i created to show how it can use shadow==closed & MUI
There are actually 2 examples, one is yours updated and the other one is mine (inspired by [remount](https://github.com/rstacruz/remount)  which is much easier than creating a proxy and playing with reflection).


[example.zip](https://github.com/bitovi/react-to-webcomponent/files/11190116/example.zip)

**Comment by zerico007** [comment]
shadow is now an option you can pass to the new [r2wc](https://www.npmjs.com/package/@r2wc/react-to-web-component)
